name: busecke_etal_2022_aguadv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.3.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - astropy=5.1=py39hd257fcd_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blosc=1.21.1=h83bc5f7_3
  - bokeh=2.4.3=py39hf3d152e_0
  - boost-cpp=1.74.0=h75c5d50_8
  - branca=0.5.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1011
  - cartopy=0.20.3=py39hed214b2_1
  - certifi=2022.6.15=py39hf3d152e_0
  - cf_xarray=0.7.3=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_0
  - cfitsio=4.1.0=hd9d235c_0
  - cftime=1.6.1=py39hd257fcd_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.1.3=py39hf3d152e_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - cmip6_preprocessing=0.6.0=pyhd8ed1ab_0
  - cmocean=2.0=py_3
  - colorspacious=1.1.2=pyh24bf2e0_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - curl=7.83.1=h2283fc2_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39hb9d737c_2
  - dask=2022.6.1=pyhd8ed1ab_0
  - dask-core=2022.6.1=pyhd8ed1ab_0
  - debugpy=1.6.0=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2022.6.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esmf=8.2.0=mpi_mpich_h4975321_100
  - esmpy=8.2.0=mpi_mpich_py39h8bb458d_101
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fastprogress=1.0.2=pyhd8ed1ab_0
  - fiona=1.8.21=py39h54775ec_2
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=2022.5.0=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_5
  - gdal=3.5.0=py39h85832e7_5
  - geopandas=0.11.0=pyhd8ed1ab_0
  - geopandas-base=0.11.0=pyha770c72_0
  - geos=3.11.0=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_2
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - h5netcdf=1.0.1=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py39h63b1161_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=mpi_mpich_h5d83325_4
  - heapdict=1.0.1=py_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.4.0=py39hf3d152e_0
  - jedi=0.18.1=py39hf3d152e_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hf3d152e_0
  - kealib=1.4.15=hfe1a663_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.3=py39hf939315_0
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libcurl=7.83.1=h2283fc2_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgdal=3.5.0=h0c20829_5
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.8.1=mpi_mpich_hcdf9059_2
  - libnghttp2=1.47.0=he49606f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=h21135ba_2
  - libpq=14.4=he2d8382_0
  - librttopo=1.1.0=hf730bdb_11
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h38b5f51_18
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hc85c160_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_3
  - libzip=1.9.2=hc929e4a_0
  - libzlib=1.2.12=h166bdaf_1
  - llvmlite=0.36.0=py39h1bbdace_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.0.0=py39h029007f_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py39h98787fa_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mpi=1.0=mpich
  - mpi4py=3.1.3=py39h32b9844_1
  - mpich=4.0.2=h846660c_100
  - msgpack-python=1.0.4=py39hf939315_0
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py39hf3d152e_5
  - nc-time-axis=1.4.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf-fortran=4.5.4=mpi_mpich_h1364a43_0
  - netcdf4=1.6.0=nompi_py39hf5a3a3f_100
  - networkx=2.8.4=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numba=0.53.1=py39h56b8d98_1
  - numcodecs=0.10.0=py39h5a03fae_1
  - numpy=1.23.0=py39hba7629e_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.4=h166bdaf_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py39h1832856_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py39hde42818_1002
  - pillow=9.2.0=py39hae2aec6_0
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - poppler=22.04.0=h1434ded_1
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.4=ha7cec9f_0
  - proj=9.0.1=h93bde94_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyerfa=2.0.0.1=py39hd257fcd_2
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.3.1=py39hdcf6798_1
  - pyshp=2.3.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.13=h2660328_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39headdf64_0
  - rasterio=1.2.10=py39h082961e_7
  - readline=8.1.2=h0f457ee_0
  - rechunker=0.5.0=pyhd8ed1ab_0
  - regionmask=0.9.0=pyhd8ed1ab_0
  - requests=2.28.1=pyhd8ed1ab_0
  - rtree=1.0.0=py39hb102c33_1
  - scikit-learn=1.1.1=py39h4037b75_0
  - scipy=1.8.1=py39he49c0e8_0
  - setuptools=63.1.0=py39hf3d152e_0
  - shapely=1.8.2=py39h68ae834_3
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sparse=0.13.0=pyhd8ed1ab_0
  - sqlite=3.39.0=h4ff8645_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.9.5=h3f4058f_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzcode=2022a=h166bdaf_0
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xarray=2022.3.0=pyhd8ed1ab_0
  - xarrayutils=1.1.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h55805fa_5
  - xesmf=0.6.3=pyhd8ed1ab_1
  - xgcm=0.8.0=pyhd8ed1ab_0
  - xhistogram=0.3.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2022.6.0=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zarr=2.12.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_2
  - pip:
    - cmip6-omz==0.1.0
prefix: /scratch/gpfs2/jbusecke/conda_tigressdata/envs/busecke_etal_2022_aguadv
